Feature: send email with jwt and verify
bcgov/reggie pull request #9
Opened 2019-01-21 17:06 UTC by ShellyXueHan

2019-01-22 23:46 UTC, patricksimonian requested changes

2019-01-22 23:46 UTC, patricksimonian commented on src/libs/email-utils.js
> +  const token = jwt.sign({ data: emailAddress }, process.env.EMAIL_JWT_SECRETE, {
`EMAIL_JWT_SECRET`

2019-01-23 00:11 UTC, ShellyXueHan commented
@patricksimonian ready for review. btw I need to put the spread for the `accountStatus` in, otherwise it's be adding the param in the outside object.

2019-01-23 20:03 UTC, patricksimonian approved these changes

2019-01-23 20:03 UTC, merged